# Generated by Django 5.2.7 on 2025-10-29 18:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tag_nfc', models.CharField(help_text='Usado para consulta pública', max_length=50, unique=True, verbose_name='ID da Tag NFC/QR Code')),
                ('nome', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=100)),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('foto_url', models.URLField(blank=True, max_length=255, null=True)),
                ('historico_veterinario', models.TextField(blank=True)),
                ('cuidados_essenciais', models.TextField(blank=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('admin_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Admin Responsável')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animais',
                'ordering': ['nome'],
            },
        ),
    ]
