# Generated by Django 5.2.7 on 2026-01-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_animal_foto_url_animal_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=10, null=True),
        ),
    ]
